### get all secrets
http://localhost:3000/secrets

### get one secret by id
http://localhost:3000/secrets/76

### get attachment for secret with id
http://localhost:3000/attachments/73

### delete secret with id
DELETE http://localhost:3000/secrets/delete/75

### search secrets by label
http://localhost:3000/search?q=cat

### post new secret
POST http://localhost:3000/secrets/new
Content-Type: application/json

{
    "label": "xxx",
    "icon": "email",
    "category": "email",
    "attachments": ["one", "two"],
    "secret": {
        "username": "xxx",
        "password": "xxx",
        "color": "xxx"
    }
}

### update secret by id
PATCH http://localhost:3000/secrets/update
Content-Type: application/json

{
    "secretId": 6,
    "label": "updated secret",
    "icon": "email",
    "category": "email",
    "secret": {
        "username": "ion",
        "password": "pretty_str0ng_passw0rd",
        "color": "red"
    }
}