### get all secrets
http://localhost:3000/all

### get one secret by id
http://localhost:3000/secret/8


### search secrets by label
http://localhost:3000/search?q=yaho

### post new secret
POST http://localhost:3000/new-secret
Content-Type: application/json

{
    "label": "yahoo",
    "secret": {
        "username": "yahoo",
        "password": "strongpassword",
        "color": "pink"
    }
}

### update secret by id
PATCH http://localhost:3000/update-secret
Content-Type: application/json

{
    "secretId": 15,
    "label": "updated secret 4",
    "secret": {
        "username": "new username 4",
        "password": "even stronger password",
        "color": "red"
    }
}