version: '3.4'

services:
    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379
        volumes:
            - ./volumes/redis:/data
        restart: unless-stopped
    nodepasswordmanager:
        image: nodepasswordmanager
        build:
        context: services/APP
        dockerfile: ./Dockerfile
        environment:
        NODE_ENV: production
        ports:
        - 3000:3000